### ISSUE TITLE
Option pour désactiver le chiffrement

### ISSUE THREAD

**Issue by rnollet** [hamzaouaddafe/AnnonceManager#1]
Est-il possible d’ajouter une option au serveur et au client qui permette de désactiver le chiffrement ? Cette fonctionnalité permettrait d’utiliser tcpdump pour comprendre exactement ce qui circule sur le réseau.

**Comment by hamzaouaddafe** [comment]
à propos de chiffrement monsieur nous j'ai chercher dans la documentation des SSLSocket de java 8. ils existe pas d'une options pour désactiver le chiffrement, ils nous reste de vous fournir un Serveur TCP et Client TCP sans SSL. Si vous voulez bien-sur ?

**Comment by hamzaouaddafe** [comment]
concernant la version sans chiffrement, monsieur. Nous avons implémenté un serveur tcp et client tcp sans sécurité, pour tester : 

**il faut lancé le serveur sans passé par _make.**

  ```
>> javac ServerTCPNotSecure.java
  >> java ServerTCPNotSecure
```

puis vous lancez le client : 
 
```
 >> javac ClientTCPNotSecure.java
 >> java ClientTCPNotSecure
```

puis pour éxécuté la commande tcpdump : 

`>>  tcpdump -i lo -v port 1027 -n -X -v -s 1514`

**Comment by rnollet** [comment]
Je ne suis pas étonné par le fait que SSL ne fournit pas d’option permettant de ne pas utiliser SSL.
Mais si vous savez écrire deux serveurs différents, normalement vous savez en écrire un seul qui contient un `if` et qui se comporte comme l’un ou l’autre selon, par exemple, qu’on lui a passé ou non une option `--no-encryption`, non ?
Est-ce que c’est clair, ce que je raconte ? Est-ce que vous trouvez que ça a du sens ?

Mais ok pour votre solution ; je me satisferai de deux serveurs et deux clients différents.

**Comment by rnollet** [comment]
Bien que ça ne soit pas lié et que ça n’ait pas beaucoup d’importance, j’en profite :
- pourquoi est-ce que vous passez deux fois l’option `-v` à `tcpdump` ?
- pourquoi est-ce que vous fixez la limite de ce qui est lu dans les paquets à `1514` ?

**Comment by hamzaouaddafe** [comment]
1 - enfaîte j'ai pas fait attention que j'ai passé -v 2 fois.
2 - je la fixer parce que -s oblige d'avoir un argument qui représente la taille des paquets. Le choix de 1514 est par hasard, est-ce  qu'il y'a une option pour prendre une taille non fixe ?

**Comment by rnollet** [comment]
Vous avez essayé sans l’option `-s` ?

**Comment by hamzaouaddafe** [comment]
Oui enfaîte j'ai suivi la documentation : https://www.tcpdump.org/manpages/tcpdump.1.html

**Comment by hamzaouaddafe** [comment]
Monsieur pour votre modification et refonte de makefile. Sinon nous avons changé la manière comment lancer le server et le client dans le commit c9782c3ca69c55c5317a003e06d1bbdddc1e6f90, nous avons ajouté une option `no-encryption` si vous tapez l'option le serveur/client lance la version qui utilise le chiffrement, sinon il lance la version qui n'utilise pas le chiffrement, ex. : 

- **sans chiffrement :**

```
>> make
>> java ServerTCP no-encryption
>> java ClientTCP no-encryption
```

- **avec chiffrement :** 

```
>> make
>> java ServerTCP 
>> java ClientTCP
```

**Comment by hamzaouaddafe** [comment]
oui vous avez raison monsieur concernant la commande de `tcpdump `, enfaite j'ai simplement essayé avec `tcpdump -i lo port 1027 -X`, sans `-s` et sans précisé la taille des paquets et sans `-v`.

Merci.

**Comment by rnollet** [comment]
Excellent pour l’option. Je pense qu’on peut fermer cette issue.
