### ISSUE TITLE
Indentation cohérente du code

### ISSUE THREAD

**Issue by rnollet** [hamzaouaddafe/AnnonceManager#2]
L’indentation du code est complètement incohérente. Pouvez-vous l’indenter correctement pour faciliter sa lecture ? Si vous n’avez pas envie de vous fatiguer, je suggère l’utilisation d’un outil automatique.
- D’après mes recherches à ce sujet, [google-java-format](https://github.com/google/google-java-format/) est le plus simple à installer et utiliser.
- L’archive à télécharger est celle qui contient `-all-deps`.
- Je serai plus heureux si vous utilisez l’option `-a`, mais faites comme vous le sentez.

**Comment by hamzaouaddafe** [comment]
Oui monsieur, nous avons réussi d'indenter correctement le code, enfaîte nous avons utilisé google-java-format comme plugin dans Eclipse. La version maintenant est dans master.

**Comment by rnollet** [comment]
Super, merci !
(J’en profite, à tout hasard : je ne sais pas si vous le savez mais vous pouvez mentionner des commits dans un commentaire en copiant leur hash. Par exemple, ici, cette issue a été réalisée par les commits 2aaae43e4153618d4e4985ddd64722240710d0df et c01a881d3aff5a135fe0d46859a3320298362109.)
